webhookURL: https://discord.com/api/webhooks/

enableDiscordWebhook: false
enablePluginReportCategories: false
enableBugReportNotifications: true

# # Available placeholders:
#
# Aqua, Black, Blue, Dark_Aqua, Dark_Blue
# Dark_Gray, Dark_Green, Dark_Purple, Dark_Red
# Gold, Gray, Green, Light_Purple, Red, White, Yellow
discordEmbedColor: Green
discordEmbedTitle: New Bug Report
discordEmbedFooter: Bug Report v0.7.1
discordEmbedThumbnail: https://www.spigotmc.org/data/resource_icons/110/110732.jpg
discordEnableThumbnail: true
discordEnableUserAuthor: true
discordIncludeDate: true

useTitleInsteadOfMessage: false
enablePlayerHeads: true
refreshPlayerHeadCache: 1d # Default, 1m, 1h, 1d, 1w, 1mo, 1y

language: en
max-reports-per-player: 50 # 0 = unlimited
report-confirmation-message: Thanks for submitting a report!

# # Available placeholders:
#
# Aqua, Black, Blue, Dark_Aqua, Dark_Blue
# Dark_Gray, Dark_Green, Dark_Purple, Dark_Red
# Gold, Gray, Green, Light_Purple, Red, White, Yellow
pluginColor: Yellow
pluginTitle: '[Bug Report]'

# This can either be "mysql" or "local".
# If you choose "mysql", you must fill out the database section below.
# If you choose "local", no configuration is required.
databaseType: local
database:
  host: localhost
  port: 3306
  database: database
  username: root
  password: password

reportCategories:
  - name: Plugin Bug
    id: 1
    description: Report a bug with a plugin
    item: minecraft:book
    color: red
  - name: Server Bug
    id: 2
    description: Report a bug with the server
    item: minecraft:emerald
    color: green
  - name: Resource Bug
    id: 3
    description: Report a bug with the resource pack
    item: minecraft:map
    color: blue
  - name: Other
    id: 4
    description: Report something else
    item: minecraft:paper
    color: yellow