name: BugReport
version: 1.0
main: com.leon.bugreport.BugReportPlugin
api-version: 1.13
commands:
  bugreport:
    description: Submit a bug report
    usage: /bugreport <message>
    executor: com.leon.bugreport.BugReportCommand
  buglist:
    description: View bug reports
    usage: /buglist
    executor: com.leon.bugreport.BugListCommand
