name: BugReport
version: 0.2.0
main: com.leon.bugreport.BugReportPlugin
api-version: 1.13
commands:
  bugreport:
    aliases:
      - br
    description: Submit a bug report
    usage: /bugreport <message>
    executor: com.leon.bugreport.BugReportCommand
  buglist:
    aliases:
      - bl
    description: View bug reports
    usage: /buglist
    executor: com.leon.bugreport.BugListCommand
  buglinkdiscord:
    aliases:
      - bld
    description: Link a Discord webhook to the server
    usage: /buglinkdiscord <Webhook URL>
    executor: com.leon.bugreport.LinkDiscordCommand