name: BugReport
version: 0.9.0
main: com.leon.bugreport.BugReportPlugin
api-version: 1.13
author: ItsLeon15
softdepend: [PlaceholderAPI, Plan]

commands:
  bugreport:
    aliases:
      - br
      - report
    description: Submit a bug report
    usage: /bugreport <message>
    executor: com.leon.bugreport.BugReportCommand
  buglist:
    aliases:
      - bl
      - reports
    description: View bug reports
    usage: /buglist
    executor: com.leon.bugreport.BugListCommand
  buglinkdiscord:
    aliases:
      - bld
    description: Link a Discord webhook to the server
    usage: /buglinkdiscord <Webhook URL>
    executor: com.leon.bugreport.LinkDiscordCommand
  buglistarchived:
    aliases:
      - bla
      - archivedreports
    description: Lists all archived bug reports
    usage: /buglistarchived
    executor: com.leon.bugreport.BugListArchivedCommand
  buglistsettings:
    aliases:
      - bls
    description: View the plugin settings
    usage: /buglistsettings
    executor: com.leon.bugreport.BugListSettingsCommand